#%RAML 1.0 Library
types:
    errorPayload:
      type: object
      properties:
        code:
          type: integer
          required: true
        message:
          type: string
          required: true
        description:
          type: string
          required: true
        dateTime:
          type: string
          required: true
        transactionId:
          type: string
          required: true