#%RAML 1.0 Trait

uses:
  CovidCaseLib: ../libraries/covidCaseLibrary.raml
responses:
  503:
    description: System connectivity failure (i.e Database is down)
    body:
      application/json:
        type: CovidCaseLib.errorPayload
        example:
              { 
                "code":503,
                "message":"Service unavailable",
                "description":"The (upstream) service is temporarily   not available",
                "dateTime":"2021-05-31T06:18:02Z",
                "transactionId":"48n32920-69ne-47b4-907d-fa15869f3c4d"
              }
  500:
    description: Internal server error
    body:
      application/json:
        type: CovidCaseLib.errorPayload
        example:
              {
                "code":500,
                "message":"Internal server error",
                "description":"The server encountered an unexpected condition which prevented it from fulfilling the request",
                "dateTime":"2021-05-31T06:18:02Z",
                "transactionId":"48n32920-69ne-47b4-907d-fa15869f3c4d"
              }
